apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.eventstoreName }}
  labels:
    app: {{ .Values.eventstoreName }}
    author: {{ .Values.author }}
spec:
  ports:
    - port: 2113
      name: grpc-ext
  selector:
    app: {{ .Values.eventstoreName }}
    author: {{ .Values.author }}