/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("de.cassisi.catalogue.kotlin-application-conventions")
    id("de.cassisi.catalogue.kotlin-infrastructure-conventions")
}

dependencies {
    implementation(project(":adapter"))
}

application {
    // Define the main class for the application.
    mainClass.set("de.cassisi.catalogue.app.AppKt")
}
