apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: student-projector
build:
  artifacts:
    - image: docker.informatik.hs-furtwangen.de/cassisid/student-projector
      jib: {}

deploy:
  helm:
    releases:
      - name: student-projector
        chartPath: charts/student-projector
        artifactOverrides:
          image: docker.informatik.hs-furtwangen.de/cassisid/student-projector