package de.cassisi.lending.student.matriculation

import de.cassisi.lending.student.BaseStudentRepository
import de.cassisi.lending.student.StudentEventStoreRepository

class UpdateMatriculationStatusEventStoreRepository(repository: StudentEventStoreRepository) : UpdateMatriculationStatusRepository, BaseStudentRepository(repository)