author: cassisid
app: catalogue-search-projector
eventstoreName: catalogue-eventstore
replicaCount: 1
image: docker.informatik.hs-furtwangen.de/cassisid/catalogue-search-projector:latest
requestMem: 256Mi
limitMem: 1024Mi
connectionString: esdb://catalogue-eventstore:2113?tls=false&keepAliveTimeout=10000&keepAliveInterval=10000
elasticsearch:
  host: "catalogue-search-elasticsearch-master"
  port: 9200