apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
    author: {{ .Values.author }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
      author: {{ .Values.author }}
  template:
    metadata:
      name: {{ .Values.app }}
      labels:
        app: {{ .Values.app }}
        author: {{ .Values.author }}
    spec:
      containers:
        - name: {{ .Values.app }}-container
          image: "{{ .Values.image }}"
          env:
            - name: eventstore.connection-string
              value: {{ .Values.connectionString }}
            - name: elasticsearch.host
              value: "{{ .Values.elasticsearch.host }}"
            - name: spring.elasticsearch.port
              value: "{{ .Values.elasticsearch.port }}"
          resources:
            limits:
              memory: {{ .Values.limitMem }}
            requests:
              memory: {{ .Values.requestMem }}
          livenessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /actuator/health/readiness
              port: 8080